### ISSUE TITLE
Derived use: Volume controller for media player

### ISSUE THREAD

**Issue by hugokernel** [TheUnlimited64/tuya_smart_knob_blueprint#3]
Is it possible to use this blueprint in a more generic way, for example to modify the volume of a media player?

**Comment by TheUnlimited64** [comment]
Yes it is totally possible. You can use it however you want. In the executed rotation action theres `delta_value` exposed. The blueprint technically only responds to the output of the smart knob and provides you with the `delta_value` which says how much it turned

According to perplexity.ai:
```
rotation_action:
  - service: media_player.volume_set
    target:
      entity_id: media_player.living_room_speaker
    data:
      volume_level: >
        {% set current = state_attr(media_player.living_room_speaker, 'volume_level') | float %}
        {% set new_level = current + (delta_value * 0.1) %}
        {{ [0, new_level, 1] | sort[1] }}
```
`delta_value` contains 1 per tick. So every "click" you feel when turning is 1. If you turn fast, its for example 3.

**Comment by hugokernel** [comment]
Thank you.

It works very well, I had to make these adaptations that may be useful to someone:

```yaml
[...]
          volume_level: >
            {% set current_level = state_attr('media_player.xxx', 'volume_level') | float(0.5) %}
            {% set delta = delta_value | float(0) %}
            {{ current_level + (delta * 0.01) }}
[...]
```

And in Z2M, in the "Device (specific)" tab of the device, I had to set the Delta value to 1.

ps: there is type in your example: `sort[1]` -> sort(1)

**Comment by hugokernel** [comment]
Full working example:

```yaml
alias: Volume du player via Smart Knob
description: ""
use_blueprint:
  path: TheUnlimited64/blueprint.yaml
  input:
    brightness_sensor: sensor.tuya_smart_knob_action_brightness_delta
    click_sensor: sensor.tuya_smart_knob_action
    rotation_action:
      - target:
          entity_id: media_player.xxx
        data:
          volume_level: >
            {% set current_level = state_attr('media_player.xxx', 'volume_level') | float(0.5) %}
            {% set delta = delta_value | float(0) %}
            {{ current_level + (delta * 0.01) }}
        action: media_player.volume_set
    click_action:
      - target:
          entity_id: media_player.xxx
        action: |
          {% if is_state('media_player.xxx', 'on') %}
            media_player.turn_off
          {% else %}
            media_player.turn_on
          {% endif %}
```
