### ISSUE TITLE
No brightness change

### ISSUE THREAD

**Issue by toniGrabulosa** [TheUnlimited64/tuya_smart_knob_blueprint#5]
Hello!

Thx for your blueprint, I got it working 50%.

Now I can turn on and turn off my light, however when rotating the knob it does nothing.

Here is my blueprint yaml (basically copypasted/adapted from your readme):

```yaml
alias: Universal Smart Knob Control
description: ""
use_blueprint:
  path: TheUnlimited64/blueprint.yaml
  input:
    brightness_sensor: sensor.smart_knob_action_brightness_delta
    click_sensor: sensor.smart_knob_action
    rotation_action:
      - target:
          entity_id: light.encimera
        data:
          brightness_step_pct: "{{ delta_value * 10 }}"
          transition: 0.5
        action: light.turn_on
    click_action:
      - target:
          entity_id: light.encimera
        action: light.toggle
        data:
          transition: 0.5
```

Notice that my light, is a MagicHome Led controller connected to a led strip.

I can dimm it trough the HA dashboard, though.

Any help would be appreciated! Thx!
